### ISSUE TITLE
Add support for specifying package dependencies

### ISSUE THREAD

**Issue by tmds** [xoofx/dotnet-releaser#14] opened 2022-02-04 02:33 UTC
It would be nice if there was a way to specify package dependencies.

For example, a .NET app could depend on `postgresql-server` package. And when the rpm gets installed, the dependencies get installed as well.

Can framework-dependent .NET apps be packaged?
If so, this can be used to add a dependency like: `dotnet-runtime-6.0`. 

cc @xoofx

**Comment by xoofx** [comment] 2022-02-04 04:11
> Can framework-dependent .NET apps be packaged?

So, currently, nope. The focus was to provide a way to easily publish x-plat app including Windows that doesn't have any package manager at the level of what deb/rpm are providing, so hence why it is supporting only single file app and it is specifying the RID (RuntimeIdentifier) when compiling the app.

As you mention, the problem is that framework dependent apps could only work for e.g debian or rpm, so that limits the usability - but definitely fine for such platforms.

> It would be nice if there was a way to specify package dependencies.

That case should be possible for deb/rpm packages without much changing the way dotnet-releaser is working. Let me check.

**Comment by xoofx** [comment] 2022-02-04 05:15
> It would be nice if there was a way to specify package dependencies.

This should be fixed by commit 00e9cbe and part of `0.1.10+`

A package dependency can be [added to the configuration file](https://github.com/xoofx/dotnet-releaser/blob/0a430727d7d98b503db4d908376b2a2d1cc87cfb/doc/readme.md#29-package-dependencies) like this:

```toml
[[deb.depends]]
name = "your-runtime-dependency"
```

For creating apps with .NET framework dependency, I will postpone it for now. Let's see if there are more demands for such a scenario.

**Closed by xoofx** 2022-02-04 05:15 UTC
Labels: enhancement

**Comment by tmds** [comment] 2022-02-04 07:27
Thank you!

> For creating apps with .NET framework dependency, I will postpone it for now. Let's see if there are more demands for such a scenario.

The main benefit is that you don't need to rebuild your app for .NET patch releases.
I wouldn't mind taking a shot at it.

**Comment by xoofx** [comment] 2022-02-04 15:52
> The main benefit is that you don't need to rebuild your app for .NET patch releases.

Yeah, I understand the use case, when you are ok that it requires to install a .NET runtime machine wide, but it's a deal breaker for anyone outside the .NET ecosystem. One reason why Go has been so popular for writing apps. One reason why I made this project, to allow to more easily target multiple platforms without having a dependency to a .NET runtime.

> I wouldn't mind taking a shot at it.

Yep, PR welcome if you want to push for such an option. 

The case of "creating a cross platform framework dependent" via `dotnet publish` alone might require some tweaks around in the current code base, as you would not have anymore the concept of RID, and the code currently is assuming that it is setup.
Hope it will not complicate to much existing code path but you will see...
